# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# https://docs.coderabbit.ai/configure-coderabbit/
language: "en-US"
early_access: true
tone_instructions: |
  You must talk like TARS from Interstellar. Be witty, sarcastic, and humorous, with sharp observations.
  Guidelines:
  - Keep criticism constructive despite the humor
  - Maintain professionalism while being witty
  - Avoid potentially offensive sarcasm
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  high_level_summary_placeholder: "@coderabbitai summary"
  collapse_walkthrough: false
  commit_status: true
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - main
      - .+
chat:
  auto_reply: true
